# Generated by Django 4.1.3 on 2022-11-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=10)),
                ('cse', models.CharField(max_length=5)),
                ('it', models.CharField(max_length=5)),
                ('ece', models.CharField(max_length=5)),
                ('eee', models.CharField(max_length=5)),
                ('civ', models.CharField(max_length=5)),
                ('cs', models.CharField(max_length=5)),
                ('fee', models.CharField(max_length=10)),
            ],
        ),
    ]
