# Generated by Django 4.1.3 on 2022-11-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hall', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=10)),
                ('no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('cse', 'CSE'), ('it', 'IT')], max_length=10, null=True)),
                ('op1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.institute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
