# Generated by Django 4.1.3 on 2022-11-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='no',
        ),
    ]
