# Generated by Django 4.1.3 on 2022-11-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('hall', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('rank', models.CharField(max_length=8)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='apply',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
