# Generated by Django 4.1.3 on 2022-11-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_students_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('hall', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=6)),
                ('college', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=5)),
                ('fee', models.CharField(max_length=10)),
            ],
        ),
    ]
