# Generated by Django 4.1.3 on 2022-11-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_allotment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allotment',
            old_name='hall',
            new_name='hall_ticket',
        ),
        migrations.RenameField(
            model_name='apply',
            old_name='op1',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='hall',
            new_name='hall_ticket',
        ),
        migrations.AlterField(
            model_name='apply',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CIV', 'CIV'), ('CS', 'CS')], max_length=10, null=True),
        ),
    ]
