# Generated by Django 4.1.3 on 2022-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_hall_allotment_hall_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='civ',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institute',
            name='cs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institute',
            name='cse',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institute',
            name='ece',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institute',
            name='eee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institute',
            name='fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='institute',
            name='it',
            field=models.IntegerField(),
        ),
    ]
