# Generated by Django 4.1.3 on 2022-11-21 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_institute_civ_alter_institute_cs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('cse', models.IntegerField()),
                ('it', models.IntegerField()),
                ('ece', models.IntegerField()),
                ('eee', models.IntegerField()),
                ('civ', models.IntegerField()),
                ('mec', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='apply',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('CIV', 'CIV'), ('MEC', 'MEC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.institution'),
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
    ]
